version: '3'

name: pg-transactional-outbox-tests

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # The host-port could be left dynamic but resilience tests start/stop PG which results in differen ports
      - 60399:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped

volumes:
  postgres-data:
